#!/bin/bash
#
# DNAOS Cross-compile toolchain compilation script                     
# Copyright (C) 2009, 2011 nfournel, TIMA Laboratory                   
#                                                                      
# This program is free software: you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or    
# (at your option) any later version.                                  
#                                                                      
# This program is distributed in the hope that it will be useful,      
# but WITHOUT ANY WARRANTY; without even the implied warranty of       
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        
# GNU General Public License for more details.                         
#                                                                      
# You should have received a copy of the GNU General Public License    
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

BINUTILS_CFLAGS=

GCC_CFLAGS=

NEWLIB_CFLAGS=

GDB_CFLAGS="-DHAVE_DECL_STPCPY=1"

#
# Define the temporary directories
#

HERE=`pwd`

NB_PROC=`cat /proc/cpuinfo | grep "processor" | wc -l`

if [ "${SEQUENTIAL}" == "yes" ]; then
	JOPT=-j1
else
	JOPT=-j${NB_PROC}
fi

SRC_DIR=$PWD

#MULTILIB_OPT=--disable-multilib
MULTILIB_OPT=--enable-multilib

#
# Sources definitions
#

# binutils stuffs
BINUTILS_BASE=binutils
BINUTILS_DIR=${BINUTILS_BASE}

# GCC stuffs
GCC_BASE=gcc
GCC_DIR=${GCC_BASE}

# Newlib stuffs
NEWLIB_BASE=newlib
NEWLIB_DIR=${NEWLIB_BASE}

# gdb stuffs
GDB_BASE=gdb
GDB_DIR=${GDB_BASE}

#
# Outputs Functions
#

if [ -t 1 ] ; then # stdout in terminal
	case "$(tput colors)" in
		256)
			INFO_LINE_COLOR="$(tput sgr0)"                  # White
			INFO_TEXT_COLOR="$(tput bold)$(tput setaf 46)"  # Green

			ERROR_LINE_COLOR="$(tput bold)$(tput setaf 9)"  # Red
			ERROR_TEXT_COLOR="$(tput bold)$(tput setaf 9)"  # Red
			NO_COLOR="$(tput sgr0)"
			;;
		*)
			INFO_LINE_COLOR="$(tput bold)$(tput setaf 3)"   # Yellow
			INFO_TEXT_COLOR="$(tput bold)$(tput setaf 6)"   # Blue

			ERROR_LINE_COLOR="$(tput bold)$(tput setaf 2)"  # Red
			ERROR_TEXT_COLOR="$(tput bold)$(tput setaf 2)"  # Red
			NO_COLOR="$(tput sgr0)"
			;;
	esac
else # stdout in file !!!
	INFO_LINE_COLOR=""
	INFO_TEXT_COLOR=""

	ERROR_LINE_COLOR=""
	ERROR_TEXT_COLOR=""

	NO_COLOR=""
fi

print_greatings()
{

    echo -en ${INFO_LINE_COLOR}
    echo     "==================================="
    echo -n  "="
    echo -en ${INFO_TEXT_COLOR}
    echo -en " Installing DNAOS Toolchain      "
    echo -en ${INFO_LINE_COLOR}
    echo "="
    echo "==================================="

    echo -en ${NO_COLOR}

    echo "Install dir  : "${INSTALL_DIR}
    echo "Build dir    : "${TMP_DIR}
    echo "To autopsy failed steps, you can find logs in 'logs' dir of each build dir"
}

print_step()
{
    echo -en ${INFO_LINE_COLOR}
    echo "==================================="
    echo -en ${INFO_TEXT_COLOR}
    echo " "$1
    echo -en ${INFO_LINE_COLOR}
    echo "==================================="
    echo -en ${NO_COLOR}
}

print_substep()
{
    echo "* "$1
}

print_error()
{
    echo -en ${ERROR_LINE_COLOR}
    echo "!---------------------------------!"
    echo "! "$1
    echo "!---------------------------------!"
    echo -en ${NO_COLOR}
}

install_error(){
    print_error "Error in installation ..."
	false # make script return FAILURE
    exit 
}

#
# Installation functions
#

binutils_install()
{
  print_step "Installing "${BINUTILS_BASE}

  cd ${TMP_DIR}

  rm -fr binutils_build
  mkdir -p binutils_build
  cd binutils_build

  mkdir -p logs

  print_substep "configuring ..."
  CFLAGS=${BINUTILS_CFLAGS}             \
  ${SRC_DIR}/${BINUTILS_DIR}/configure  \
  --prefix=${INSTALL_DIR}               \
  --target=${TARGET}                    \
  ${BINUTILS_EXTRA_OPTS}                \
  --disable-nls                         \
  --disable-werror                      \
  ${MULTILIB_OPT}     &> logs/configure.log || return

  print_substep "compiling ..."
  make ${JOPT}          &> logs/make.log      || return

  print_substep "installing ..."
  make install ${JOPT}  &> logs/install.log   || return

  touch ${STAMPS_DIR}/binutils_installed
}

gcc_1_install()
{
  print_step "Installing "${GCC_BASE}" bootstrap"

  cd ${TMP_DIR}

  rm -fr gcc_build
  mkdir -p gcc_build
  cd gcc_build

  mkdir -p logs

  print_substep "configuring ..."

  CFLAGS=${GCC_CFLAGS}              \
  ${SRC_DIR}/${GCC_DIR}/configure   \
  --prefix=${INSTALL_DIR}           \
  --target=${TARGET}                \
  ${GCC_EXTRA_OPTS}                 \
  --disable-nls                     \
  --with-system-zlib                \
  --with-newlib                     \
  --enable-interwork                \
  ${MULTILIB_OPT}                   \
  --enable-languages=c,c++         &> logs/configure.log || return

  print_substep "compiling ..."
  make all-gcc ${JOPT}      &> logs/make_1.log    || return

  print_substep "installing ..."
  make install-gcc ${JOPT}  &> logs/install_1.log || return

  touch ${STAMPS_DIR}/gcc_1_installed
}

newlib_install()
{
  print_step "Installing "${NEWLIB_BASE}

  cd ${TMP_DIR}

  rm -fr newlib_build
  mkdir -p newlib_build
  cd newlib_build

  mkdir -p logs

  print_substep "configuring ..."
  CFLAGS=${NEWLIB_CFLAGS}                 \
  ${SRC_DIR}/${NEWLIB_DIR}/configure      \
  --prefix=${INSTALL_DIR}                 \
  --target=${TARGET}                      \
  ${NEWLIB_EXTRA_OPTS}                    \
  ${MULTILIB_OPT}                         \
  --disable-nls                           \
  --enable-interwork                      \
  --enable-newlib-io-long-long            \
  --enable-newlib-io-long-double          \
  --enable-newlib-io-c99-formats          \
  --disable-newlib-may-supply-syscalls    \
  --enable-newlib-multithread             \
  --disable-newlib-supplied-syscalls      &> logs/configure.log || return

  print_substep "compiling ..." 
  make ${JOPT}                            &> logs/make.log      || return

  print_substep "installing ..."
  make install ${JOPT}                    &> logs/install.log   || return

  touch ${STAMPS_DIR}/newlib_installed
}

gcc_2_install()
{
  print_step "Installing "${GCC_DIR}" final"

  cd ${TMP_DIR}/gcc_build

  print_substep "compiling ..." 
  make all ${JOPT}                   &> logs/make_2.log    || return

  print_substep "installing ..."
  make install ${JOPT}               &> logs/install_2.log || return

  touch ${STAMPS_DIR}/gcc_2_installed
}

gdb_install()
{
  print_step "Installing "${GDB_BASE}

  cd ${TMP_DIR}

  rm -fr gdb_build
  mkdir -p gdb_build
  cd gdb_build

  mkdir -p logs

  print_substep "configuring ..."
  CFLAGS=${GDB_CFLAGS}            \
  ${SRC_DIR}/${GDB_DIR}/configure \
  --prefix=${INSTALL_DIR}     \
  --target=${TARGET}          \
  ${GDB_EXTRA_OPTS}           \
  --disable-nls               \
  --disable-builtins          \
  ${MULTILIB_OPT}             &> logs/configure.log || return

  print_substep "compiling ..." 
  make ${JOPT}                &> logs/make.log      || return

  print_substep "installing ..."
  make install ${JOPT}        &> logs/install.log || return

  touch ${STAMPS_DIR}/gdb_installed
}

print_usage()
{
  echo "Usage : $1 {arm, c6x, microblaze, mips, x86, native} INSTALL_DIR"
  exit
}

#
# Main
#

if [ $# -lt 2 ]; then 
   print_usage $0
fi

case "$1" in
   arm*)           ARCH=arm ;;
   native* | x86*) ARCH=i386 ;;
   mips*)          ARCH=mips ;;
   microblaze*)    ARCH=microblaze ;;
   c6x*)           ARCH=tic6x ;;
   *)              echo "Unsupported target: $1";
                   print_usage $0 ;;
esac

TMP_DIR=$PWD/build-${ARCH}
STAMPS_DIR=${TMP_DIR}/stamps

TARGET=${ARCH}-sls-dnaos

if [ "${2:0:1}" = "/" ] ; then
  INSTALL_DIR=$2 ;
else
  INSTALL_DIR=$PWD/$2 ;
fi ;

print_greatings

mkdir -p ${TMP_DIR}
mkdir -p ${INSTALL_DIR}
mkdir -p ${STAMPS_DIR}

#
# Perform the installation process
#

[ -e ${STAMPS_DIR}/binutils_installed ] || \
    binutils_install || install_error

[ -e ${STAMPS_DIR}/gcc_1_installed ] || \
    gcc_1_install    || install_error

export PATH=$PATH:${INSTALL_DIR}/bin

[ -e ${STAMPS_DIR}/newlib_installed ] || \
    newlib_install   || install_error

[ -e ${STAMPS_DIR}/gcc_2_installed ] || \
    gcc_2_install    || install_error

[ -e ${STAMPS_DIR}/gdb_installed ] || \
    gdb_install      || install_error

print_step "Done."
